### ISSUE TITLE
Show where the reply's going to be displayed 

### ISSUE THREAD

**Issue by patrykadas** [CryptoVerseCC/tokntalk#103]
Our users don't understand exactly how we distribute the messages. Let's include small alerts and contextual information in the most crucial parts. 

![helpers](https://user-images.githubusercontent.com/6234032/44790098-abc81880-ab9e-11e8-86e4-4267d407e044.png)

**Comment by gkapkowski** [comment]
![20180830_103858](https://user-images.githubusercontent.com/114996/44840272-fdc17a80-ac40-11e8-8755-b59715b763cf.jpg)
