### ISSUE TITLE
Display domain name instead of name for external links

### ISSUE THREAD

**Issue by mg6maciej** [CryptoVerseCC/tokntalk#11]
<img width="444" alt="image" src="https://user-images.githubusercontent.com/1316369/43632590-e14dea22-9706-11e8-844c-f8bcac7ff2e2.png">

should be

<img width="402" alt="image" src="https://user-images.githubusercontent.com/1316369/43632689-264aaf70-9707-11e8-9879-bc2289db152d.png">

**Comment by patrykadas** [comment]
Instead of avatar there should be an icon of a community
