### ISSUE TITLE
Add icons "How many messages since you've last checked"

### ISSUE THREAD

**Issue by gkapkowski** [CryptoVerseCC/tokntalk#16]
On Discovery page: I would like to see small icons (5), (10), (0) next to each tile, with number of new messages since i've last opened discovery page.

Problem: Right now If I want to see what's new in my communities I need to click through each and every one of them.

**Comment by patrykadas** [comment]
![number](https://user-images.githubusercontent.com/6234032/44037147-ddf8497a-9f13-11e8-9ee1-f99e77e9f0fe.png)

Please use primaryColor and secondaryColor for the labels.
