### ISSUE TITLE
Clicking reply numbers should show list of repliers 

### ISSUE THREAD

**Issue by patrykadas** [CryptoVerseCC/tokntalk#41]
This one might need discussion, we can figure it out also in a different way.

**Comment by ghostbuster91** [comment]
Maybe clicking at the root message to which replies belong to should show a modal with this message and all replies.

**Comment by patrykadas** [comment]
@ghostbuster91 
Yes, as seen in:
https://invis.io/Y4MYB66HSPG#/309552205_CommentExpanded
