### ISSUE TITLE
"Undefined" in avatar profile

### ISSUE THREAD

**Issue by 83tb** [CryptoVerseCC/tokntalk#59]
When I switch into new avatar and click on my profile I get "undefined" everywhere where should by my "nick".

<img width="1423" alt="screen shot 2018-08-15 at 11 27 02" src="https://user-images.githubusercontent.com/733100/44141831-8d8e9ae0-a07e-11e8-96ff-286bf0c8692d.png">

To reproduce: add new erc-721 token, switch to the avatar based on this token - click on your avatar "nick" (link to profile).

**Comment by jakubsta** [comment]
Resolved in 802540d456524eec42453b3726a34643de36d825
