### ISSUE TITLE
On-chain switch should be hidden

### ISSUE THREAD

**Issue by 83tb** [CryptoVerseCC/tokntalk#62]
This option is super confusing for users and may cost them. Could be enabled under some feature flag for special users, but should not be visible on launch.

**Comment by 83tb** [comment]
<img width="880" alt="screen shot 2018-08-18 at 21 41 37" src="https://user-images.githubusercontent.com/733100/44302750-9c8bd400-a32f-11e8-807f-db0837afe13e.png">

**Comment by 83tb** [comment]
much more confused users will arrive

**Comment by patrykadas** [comment]
#122
