### ISSUE TITLE
UNCLEAR that I have to switch to "account" to take part in non-721 community #UX

### ISSUE THREAD

**Issue by 83tb** [CryptoVerseCC/tokntalk#64]
I was trying to join ZRX community, I have ZRXs. But I needed to guess that I have to switch to "account". Before I just saw that I need to "acquire ZRXs" - confusing.

**Comment by patrykadas** [comment]
It's a bug - you should be able to write as ERC721 in any ERC20 community. 
Switch error only happens, when I am viewing a NFT club that's not the same as currently selected NFT. 

@mg6maciej @jakubsta

**Comment by 83tb** [comment]
yes, certainly possible

**Comment by jakubsta** [comment]
I've just created an issue (#65) to prevent this happen in the future. Closing this issue.
