### ISSUE TITLE
Display all owned ERC-20 tokens in `Your communities`

### ISSUE THREAD

**Issue by gkapkowski** [CryptoVerseCC/tokntalk#73]
With button `Request support`/`Request adding this community`.
So that we can reduce friction in adding communities and show people what tokens they have.

Clicking `add` button would open intercom (like we have now) but with prefilled message with token address/name/symbol.

eg. message: `I request adding community: 0xABC, ABCTOKEN, ABC`

**Comment by patrykadas** [comment]
We should just redirect to the club page!
