### ISSUE TITLE
CryptoKitty not fully loaded avatar

### ISSUE THREAD

**Issue by gkapkowski** [CryptoVerseCC/tokntalk#82]
![screenshot from 2018-08-20 02-26-00](https://user-images.githubusercontent.com/114996/44315037-71cd7880-a420-11e8-9045-eacb70fb2323.png)

**Comment by gkapkowski** [comment]
https://tokntalk.club/ethereum:0x06012c8cf97bead5deae237070f9587f8e7a266d:832045

**Comment by gkapkowski** [comment]
It looks good on Cryptokitties page

**Comment by jakubsta** [comment]
The image is fully loaded but image itself is broken, check opensea response:
[openseaAPI](https://opensea-api.herokuapp.com/asset/0x06012c8cf97bead5deae237070f9587f8e7a266d/832045/)
[image_preview_url](https://storage.googleapis.com/opensea-prod.appspot.com/0x06012c8cf97bead5deae237070f9587f8e7a266d-preview/832045.png)
[image_url](https://storage.googleapis.com/opensea-prod.appspot.com/0x06012c8cf97bead5deae237070f9587f8e7a266d/832045.svg)

**Comment by mg6maciej** [comment]
I wrote about this to @OpenSeaProject @alexanderatallah a few days ago.

**Comment by mg6maciej** [comment]
Using original .svg files when available.
