### ISSUE TITLE
"Seen In" link bug

### ISSUE THREAD

**Issue by dAAAb** [CryptoVerseCC/tokntalk#87]
Some "Seen In" link in profile page seems to lack of ".com" in the end.
Which cause broken link such like : http://facebook/userid 
e.g. https://tokntalk.club/ethereum:0x06012c8cf97bead5deae237070f9587f8e7a266d:756956

**Comment by jakubsta** [comment]
@dAAAb Indeed there was a bug which was fixed in: https://github.com/CryptoVerseCC/tokntalk/commit/1f91dfc54cd18a5d3da17f079cb93e54ac423974. But unfortunately fix won't affect currently configured profiles, so you have to enter your username once again, sorry for the inconvenience.
